# **BRFSS Conversion Script: XPT to CSV**

The original BRFSS data is available from the CDC in a couple of arcane formats (.XPT and .ASCII). I have downloaded the original data from the official [website](https://www.cdc.gov/brfss/annual_data/annual_data.htm) in the .ASCII format and uploaded with the .xpt extension. Note, .XPT was converted to .xpt for uniformity. 

The code below will allow the conversion of one year of BRFSS data to .csv format at a time. You should be warned that these are pretty big files, especially in the more recent years. In this script the BRFSS data for 2015 is used as an example.

# Getting Started

Let's start by importing our libraries. We'll be using pandas and the pyreadstat package. Note, you may need to install pyreadstat first.

In [ ]:
import pandas as pd

In [ ]:
pip install pyreadstat

Requirement already satisfied: pyreadstat in /usr/local/lib/python3.7/dist-packages (1.1.2)
Requirement already satisfied: pandas>0.24.0 in /usr/local/lib/python3.7/dist-packages (from pyreadstat) (1.1.5)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas>0.24.0->pyreadstat) (1.19.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>0.24.0->pyreadstat) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>0.24.0->pyreadstat) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>0.24.0->pyreadstat) (1.15.0)

In [ ]:
import pyreadstat

# Reading in the data

To ensure the BRFSS data was downloaded completely and correctly from the CDC website the following must be true for each year of data: 

*   2015 = 441456 rows x 
*   2016 = 
*   2017 = 
*   2018 =
*   2019 = 418268 rows Ã— 342 columns

In [ ]:
df = pd.read_sas('/content/LLCP2015.xpt ',format='xport',encoding='utf-8') #upload data and save as dataframe

In [ ]:
df #confirm shape

        _STATE  FMONTH     IDATE  ... _FLSHOT7 _PNEUMO3 _AIDTST4
0          1.0     1.0  01182019  ...      2.0      1.0      2.0
1          1.0     1.0  01132019  ...      1.0      1.0      2.0
2          1.0     1.0  01182019  ...      1.0      2.0      2.0
3          1.0     1.0  01182019  ...      9.0      9.0      NaN
4          1.0     1.0  01042019  ...      2.0      1.0      2.0
...        ...     ...       ...  ...      ...      ...      ...
418263    72.0     9.0  03152020  ...      2.0      2.0      2.0
418264    72.0     9.0  03082020  ...      NaN      NaN      2.0
418265    72.0     9.0  03102020  ...      NaN      NaN      1.0
418266    72.0     9.0  03062020  ...      2.0      2.0      2.0
418267    72.0     9.0  03052020  ...      NaN      NaN      2.0

[418268 rows x 342 columns]

# Convert to .csv format

In [ ]:
df.to_csv('BRFSS_2015.csv',index=False)